import { Download, Pencil, Highlighter, MousePointer2, PenLine, Redo2, RotateCw, Shapes, Trash2, Undo2, Copy, ImagePlus, Signature, Stamp, TextCursorInput, CheckSquare } from 'lucide-react';
import { usePdfEditor } from '../hooks/usePdfEditor';
import type { EditorTool } from '../types/annotations';

const tools: Array<[EditorTool, string, typeof MousePointer2]> = [['select', 'Select', MousePointer2], ['text', 'Add text', Pencil], ['highlight', 'Highlight', Highlighter], ['draw', 'Freehand draw', PenLine], ['rectangle', 'Rectangle', Shapes], ['ellipse', 'Ellipse', Shapes], ['line', 'Line', PenLine], ['arrow', 'Arrow', RotateCw], ['image', 'Add image', ImagePlus], ['signature', 'Add visual signature', Signature], ['stamp', 'Add approved stamp', Stamp], ['form-text', 'Add text form field', TextCursorInput], ['form-checkbox', 'Add checkbox form field', CheckSquare], ['form-signature', 'Add signature form field', Signature]];

export function EditorToolbar({ onExport, exporting }: { onExport: () => void; exporting: boolean }) {
    const { activeTool, selectedIds, canUndo, canRedo, setTool, removeSelected, duplicateSelected, undo, redo } = usePdfEditor();
    return <div className="editor-toolbar" aria-label="Annotation tools"><div className="editor-toolbar__tools">{tools.map(([tool, label, Icon]) => <button key={tool} className={`icon-button${activeTool === tool ? ' is-active' : ''}`} type="button" onClick={() => setTool(tool)} aria-label={label} title={label}><Icon size={17} aria-hidden="true" /></button>)}</div><div className="editor-toolbar__actions"><button className="icon-button" type="button" onClick={undo} disabled={!canUndo} aria-label="Undo" title="Undo"><Undo2 size={17} aria-hidden="true" /></button><button className="icon-button" type="button" onClick={redo} disabled={!canRedo} aria-label="Redo" title="Redo"><Redo2 size={17} aria-hidden="true" /></button><button className="icon-button" type="button" onClick={duplicateSelected} disabled={!selectedIds.length} aria-label="Duplicate selected annotations" title="Duplicate"><Copy size={17} aria-hidden="true" /></button><button className="icon-button" type="button" onClick={removeSelected} disabled={!selectedIds.length} aria-label="Delete selected annotations" title="Delete"><Trash2 size={17} aria-hidden="true" /></button><button className="button button--secondary button--compact" type="button" onClick={onExport} disabled={exporting} aria-label="Export edited PDF"><Download size={16} aria-hidden="true" />{exporting ? 'Exporting' : 'Export'}</button></div></div>;
}
