import {
    BadgeDollarSign,
    Bot,
    Droplets,
    FileOutput,
    FilePenLine,
    FileText,
    Files,
    FolderKanban,
    House,
    LifeBuoy,
    Minimize2,
    Newspaper,
    PenTool,
    RotateCw,
    ScanText,
    Scissors,
    ShieldCheck,
} from 'lucide-react';
import type { NavigationItem, WorkspaceRoute } from '../types/navigation';

export const navigationItems: NavigationItem[] = [
    { label: 'Home', path: '/', icon: House, section: 'Workspace' },
    { label: 'Edit PDF', path: '/edit', icon: FilePenLine, section: 'Workspace' },
    { label: 'Merge PDF', path: '/merge', icon: Files, section: 'Workspace' },
    { label: 'Split PDF', path: '/split', icon: Scissors, section: 'Workspace' },
    { label: 'Compress PDF', path: '/compress', icon: Minimize2, section: 'Workspace' },
    { label: 'Organize Pages', path: '/organize', icon: FolderKanban, section: 'Workspace' },
    { label: 'Rotate PDF', path: '/rotate', icon: RotateCw, section: 'Workspace' },
    { label: 'Watermark', path: '/watermark', icon: Droplets, section: 'Workspace' },
    { label: 'Sign PDF', path: '/sign', icon: PenTool, section: 'Workspace' },
    { label: 'OCR', path: '/ocr', icon: ScanText, section: 'Workspace' },
    { label: 'Convert PDF', path: '/convert', icon: FileOutput, section: 'Workspace' },
    { label: 'AI Assistant', path: '/ai', icon: Bot, section: 'Workspace' },
    { label: 'Pricing', path: '/pricing', icon: BadgeDollarSign, section: 'Resources' },
    { label: 'Blog', path: '/blog', icon: Newspaper, section: 'Resources' },
    { label: 'Support', path: '/support', icon: LifeBuoy, section: 'Resources' },
    { label: 'Privacy', path: '/privacy', icon: ShieldCheck, section: 'Resources' },
    { label: 'Terms', path: '/terms', icon: FileText, section: 'Resources' },
];

export const workspaceRoutes: Record<string, WorkspaceRoute> = {
    '/': { title: 'PDF workspace', eyebrow: 'Home', description: 'Start with a document when PDF workflows are introduced.' },
    '/edit': { title: 'Edit PDF', eyebrow: 'Edit', description: 'A focused workspace for future document editing tools.' },
    '/merge': { title: 'Merge PDF', eyebrow: 'Organize', description: 'Prepare a document-combination workflow.' },
    '/split': { title: 'Split PDF', eyebrow: 'Organize', description: 'Prepare a page-separation workflow.' },
    '/compress': { title: 'Compress PDF', eyebrow: 'Optimize', description: 'Prepare a file-size optimization workflow.' },
    '/organize': { title: 'Organize pages', eyebrow: 'Organize', description: 'Prepare page sorting and arrangement controls.' },
    '/rotate': { title: 'Rotate PDF', eyebrow: 'Organize', description: 'Prepare bulk page-orientation controls.' },
    '/watermark': { title: 'Watermark', eyebrow: 'Edit', description: 'Prepare a watermarking workspace.' },
    '/sign': { title: 'Sign PDF', eyebrow: 'Protect', description: 'Prepare a document-signing workspace.' },
    '/ocr': { title: 'OCR', eyebrow: 'Enhance', description: 'Prepare an optical text recognition workspace.' },
    '/convert': { title: 'Convert PDF', eyebrow: 'Convert', description: 'Prepare document conversion controls.' },
    '/ai': { title: 'AI Assistant', eyebrow: 'Assistant', description: 'Prepare an optional document-assistance workspace.' },
};
